/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "Gain 1 null point(np) every second.": "每秒获得 1 个空点（np）。",
    "Currently": "当前",
    "compressed null points": "压缩空点",
    "CP gain above 1e33 are raised to 3rd power.": "高于 1e33 的 CP 增益提高到 3 次方。",
    "Base np requirement to gain cp is 50% less.": "获得 cp 的基本 空点 要求减少 50%。",
    "Automation": "自动化",
    "Multiply effect of upgrade 12 ~ 14 based on np.": "基于空点的升级12~14倍增效果。",
    "Multiply effect of upgrade 12 and 13 based on your np.": "乘以升级 12 和 13 的效果基于您的 空点.",
    "Multiply effect of upgrade based on your cp.": "根据你的cp乘以升级的效果。",
    "Multiply np gain based on your compressed null point(cp).": "根据压缩空点（cp）乘以 空点 增益。",
    "Multiply np gain based on your np.": "根据您的 空点 乘以 空点 增益。",
    "Np required to get cp grows MUCH slower.": "获得 cp 所需的 空点 增长得慢得多。",
    "Np required to get cp grows MUCH^2 slower.": "获得 cp 所需的 空点 增长慢得多^2。",
    "Np required to get cp grows slower.": "获得 cp 所需的 空点 增长较慢。",
    "null points": "空点",
    "Reset for +": "重置得到 +",
    "The Null Tree Discord": "空值树 Discord",
    "Achievement Gotten!": "成就获得！",
    "achievement power (which gives you multiplier on points generation": "成就力量（它使您获得点数的乘数",
    "Air": "气",
    "Base np requirement to gain cp is 50% less AGAIN.": "获得 cp 的基本 空点 要求再次减少 50%。",
    "Buy all auto prestige for row 2.": "购买第 2 行的所有自动声望。",
    "\"REAL\" automation": "“真正的”自动化",
    "3k infinities": "3k 无限",
    "5 dozens of infinities": "5 打无穷大",
    "Buy upgrade 11 in id.": "在 id 中购买升级 11。",
    "Earth": "地",
    "Effectively idle.": "有效放置。",
    "Energetic Energy": "高能能量",
    "Faster than a potato": "比土豆还快",
    "Finish EASY challenge once.": "完成一次 简单 挑战。",
    "Fire": "火",
    "Get a fire point.": "得到1 火 点数",
    "Get a water point.": "得到1 水 点数",
    "Get an air point.": "得到1 气 点数",
    "Get an earth point.": "得到1 地 点数",
    "Get at least x2304 energy power from upgrades in S.": "从 S 的升级中获得至少 x2304 的能量。",
    "Infinity isn't hard": "无限并不难",
    "Have at least 60 seconds of inertia.": "至少有 60 秒的惯性。",
    "Limit Break": "突破极限",
    "Nearly 1e-21 Universe": "接近 1e-21 宇宙",
    "Not so challenging": "没那么有挑战性",
    "One minute is a lot.": "一分钟很多。",
    "Reward: points in row 2 becomes much cheaper.": "奖励：第 2 行的点数变得便宜得多。",
    "Reward: These upgrades increases energy gain, and also unlockes something great.": "奖励：这些升级增加了能量增益，也解锁了一些伟大的东西。",
    "Too Much Fire": "太多的火",
    "Water": "水",
    "You gotta start somewhere...": "你必须从某个地方开始......",
    "Get 29 OoMs of np per second.": "每秒获得 29 个 OoM 的 空点。",
    "Higher Generation np/s Cap": "更高世代 空点/秒 上限",
    "Higher Inertia Cap": "更高的惯性上限",
    "Faster Inertia Generation": "更快的惯性生成",
    "More Null Points": "更多空点",
    "Produce null points at a much slower speed but always get Inertia.": "以慢得多的速度产生空点，但总是得到惯性。",
    "seconds of Inertia": "秒的惯性",
    "Off": "关",
    "On": "开",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Currently: ": "当前: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^Reach 1.00e41 compressed null points to unlock \(You have (.+) compressed null points$/, '达到1.00e41个压缩空点解锁（你有 $1 压缩空点'],
    [/^You are getting (.+) seconds of Inertia every second.$/, '您每秒获得 $1 秒的惯性。'],
    [/^You are gaining (.+) compressed null points per second$/, '您每秒获得 $1 压缩空点'],
    [/^Your Inertia is capped at (.+) seconds.$/, '您的惯性上限为 $1 秒。'],
    [/^Inertia is only generated when your np\/s isn\'t greater than (.+).$/, '惯性仅在您的 空点\/秒 不大于 $1 时生成。'],
    [/^Effect of this upgrade resets when C resets.\nCost: (.+) seconds of Inertia\n(.+)Amount: (.+)\n(.+)Effect: (.+)$/, '此升级的效果会在 C 重置时重置。\n成本：$1 秒的惯性\n$2数量：$3\n 效果：$4'],
    [/^Cost: (.+) seconds of Inertia\n(.+)Amount: (.+)\n(.+)Multiplies your np gain by (.+)$/, '成本：$1 秒的惯性\n$2数量：$3\n$4将你的 空点 增益乘以 $5'],
    [/^Cost: (.+) seconds of Inertia\n(.+)Amount: (\d+) \/ (\d+)$/, '成本：$1 秒的惯性\n$2数量：$3 \/ $4'],
    [/^You have (.+) null points$/, '你有 $1 空点数'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Get (.+) ip.$/, '获得 $1 ip'],
    [/^Get (.+) stars.$/, '获得 $1 星星'],
    [/^Get (.+) fp.$/, '获得 $1 fp'],
    [/^Get (.+) cp.$/, '获得 $1 cp'],
    [/^Next at (.+) null points$/, '下一个在 $1 空点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Buy upgrade ([\d\.]+) in C.$/, '在 C 中购买升级 $1。'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) seconds of Inertia$/, '$1 秒的惯性'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) compressed null points$/, '$1 压缩空点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Cost: (.+) compressed null points$/, '成本：$1 压缩空点'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);